name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract Git Tag
        id: git_tag
        run: echo "::set-output name=TAG::$(git describe --tags --abbrev=0)"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            starknetfoundation/starknet-dev:latest
            starknetfoundation/starknet-dev:${{ steps.git_tag.outputs.TAG }}

      - name: Log out of Docker Hub
        run: docker logout
